she_codes_news/news/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name="addNewsStory"),
    path('add-category/', views.AddCategoryView.as_view(), name="addCategory"),
    path('<int:pk>/update/', views.UpdateStoryView.as_view(), name='updateStory'),
    path('<int:pk>/delete/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
    path('category/<str:cats>/', views.CategoryView, name='category'),


]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('update-profile/', user_views.update_profile, name='updateProfile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, SignUpView


app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    # path('user-account/<int:pk>/', AccountView.as_view(), name='userAccount'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
User = settings.AUTH_USER_MODEL
from PIL import Image



class CustomUser(AbstractUser):
    pass
    def __str__(self):
        return self.username

class Profile(models.Model):
    user = models.OneToOneField(User,blank=True, null=True, on_delete=models.CASCADE)
    birth_date = models.DateField(blank=True, null=True)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_pics', blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # run the save method from the parents
        img = Image.open(self.avatar.path)
        if img.height > 300 or img.width > 300:
            output_size = (300,  300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Profile
from django.forms import ModelForm


class CustomUserCreationForm(UserCreationForm):
    
    class Meta: 
        model = CustomUser
        fields = ['username', 'email']

class CustomUserChangeForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
        exclude = ['password2', 'password1']

        labels = {
            'username': 'Choose your username:',
            'email': 'Update your email:'
        }
        widgets ={
            'username' : forms.TextInput(
                attrs={
                'class': 'text_field',
                'placeholder' : 'your username',
                }),
            'email' : forms.TextInput(
                attrs={
                    'class': 'text_field',
                    'placeholder' : 'your email',
                }),
        }
        

class ProfileUpdateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'location', 'birth_date']
        labels = {
            'birth_date': 'Update your date of birth:',
            'avatar': 'Choose your profile picture:',
            'bio': 'Update your bio',
            'location': 'Where do you write from?',
        }
        widgets ={
            'birth_date': forms.DateInput(
                # format=('%m/%d/%Y'),
                attrs={
                    'class': 'form-control text_field',
                    'type': 'date',
                }),         
            'avatar' :forms.FileInput,
            'bio' : forms.Textarea(attrs={'rows':10, 'cols':25}),
            }

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser, Profile
from .forms import CustomUserCreationForm, CustomUserChangeForm, ProfileUpdateForm
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin



class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class SignUpView(CreateView):

    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

# class UpdateProfileView(generic.UpdateView):
#     model=Profile
#     form_class = ProfileUpdateForm
#     context_object_name = 'profile'
#     template_name = 'users/updateProfile.html'
#     success_url = reverse_lazy('profile')

#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super().form_valid(form)
        

@login_required
def profile(request):
    print(request.method)
    if request.method == 'POST':
        u_form=CustomUserChangeForm(request.POST, instance=request.user)
        p_form=ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            # messages.success(request, f'Your account has been updated!')
            return redirect ('profile')

    else:
        u_form=CustomUserChangeForm(instance=request.user)
        p_form=ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

@login_required
def update_profile(request):
    if request.method == 'POST':
        u_form=CustomUserChangeForm(request.POST, instance=request.user)
        p_form=ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            # messages.success(request, f'Your account has been updated!')
            return redirect ('profile')

    else:
        u_form=CustomUserChangeForm(instance=request.user)
        p_form=ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/updateProfile.html', context)

# Try request.method == 'DELETE': to delete a profile

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block title %}Create your account{% endblock %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <p>You are laready logged in.</p>
        <a href="{% url 'news:index' %}">Go back Home</a>
    {% else %}
        <h2>Create Account</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create Account</button>
        </form>
    {% endif %}
</div="container">
{% endblock %}

she_codes_news/users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block title %}{{ user.username }} Profile{% endblock %}
{% block content %}
<div class="container container-profile">
    <img class="profile-avatar" src="{{ user.profile.avatar.url }}" alt="{{ user.username }} profile picture">
    <div>
        <ul>
            <li><span>Username</span>: {{ user.username }}</li>
            <li><span>Email</span>: {{ user.email }}</li>
            <li><span>Location:</span> {{ user.profile.location }}</li>
            <li><span>Birth Date:</span> {{ user.profile.birth_date | date:"d M Y" }}</li>
            <li><span>Bio:</span> {{ user.profile.bio }}</li>

        </ul>
    <!-- <h2>{{ user.username }} Profile</h2>
    <p>{{ user.birth_date }}</p>
    <p>{{ user.email }}</p> -->
    <!-- </div>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ u_form.as_p }}
            {{ p_form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div> -->
    <a class="btn" href=" {% url 'updateProfile'%}">Update your profile</a>


</div>

{% endblock %}

she_codes_news/users/templates/users/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container">
    {% if user.is_authenticated %}
        <p>You are already logged in.</p>
        <a href="{% url 'news:index' %}">Go back Home</a>
    {% else %}
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn">Sign up</button>
        </form>
        <h2> Do you already have an account?</h2>
        <a href="{% url 'login' %}">Login to your account</a>
    {% endif %}
</div>
{% endblock %}

she_codes_news/users/templates/users/updateProfile.html
{% extends "base.html" %}
{% load static %}
{% block title %}Update your Profile{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <h2> Update your Profile</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ u_form.as_p }}
        {{ p_form.as_p }}
        <input type="submit" value="submit" class="btn">
    </form>
</div>
{% endblock %}

she_codes_news/users/templates/users/userAccount.html
<!-- {% extends 'base.html' %}
{% block title %}{{ user }} Account{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <h2>User Account</h2>
    <p>Hello {{ user }}</p>
    <p>Your email:</p><p>{{ user.email }}</p>
    <p>Your profile picture:</p><img src="{{ user.avatar }}" alt="{{ user}} picture">
    <p>Your birth date:</p><p>{{ user.birth_date }}</p>
    <button><a href="{% url 'users:updateProfile' request.user.id %}">Update your profile</a></button>

{% else %}
    <a href="{% url 'login' %}?next={{request.path}}">Login to be able to see your profile</a>
{% endif %}


{% endblock %} -->