she_codes_news/news/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name="addNewsStory"),
    path('add-category/', views.AddCategoryView.as_view(), name="addCategory"),
    path('<int:pk>/update/', views.UpdateStoryView.as_view(), name='updateStory'),
    path('<int:pk>/delete/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
    path('category/<str:cats>/', views.CategoryView, name='category'),


]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('update-profile/', user_views.update_profile, name='updateProfile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, SignUpView


app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    # path('user-account/<int:pk>/', AccountView.as_view(), name='userAccount'),
    path('signup/', SignUpView.as_view(), name='signup'),
]

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}She Codes News{% endblock %}</title>
        <meta name="description" content="">
        <meta name="author" content="FL">
        <meta name="viewport" content="width=device-width, initial-scale=1" /> 
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock %}

    </head>

    <body>
        <div class="content">
            {% include './nav.html' %}
                <header> 
                    <a href="{% url 'news:index' %}">
                        <img src="{% static 'logo.svg' %}" alt="Cupcake Logo" width="80px">
                        <h1>She {Codes} News</h1>
                    </a>
                </header>

            <!-- content blocks here -->
            <!-- This is where the content of other template comes -->
            <main>{% block content %}{% endblock %}</main>
        </div>
            <footer>
                Copyright ©  <a href="https://shedesign.dev" title="Fanny Lefert Portfolio">SheDesign.dev</a>
            </footer>
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    {% if user.is_authenticated %}
        <a href="{% url 'profile' %}">Profile</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:signup' %}">Signup</a>
    {% endif %}
</nav>