she_codes_news/news/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name="addNewsStory"),
    path('add-category/', views.AddCategoryView.as_view(), name="addCategory"),
    path('<int:pk>/update/', views.UpdateStoryView.as_view(), name='updateStory'),
    path('<int:pk>/delete/', views.DeleteStoryView.as_view(), name='deleteStory'),
    path('author/<int:pk>', views.AuthorView.as_view(), name='author'),
    path('category/<str:cats>/', views.CategoryView, name='category'),


]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('update-profile/', user_views.update_profile, name='updateProfile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

she_codes_news/news/models.py
from django.conf import settings
from django.db import models
# from django.contrib.auth import get_user_model
from django.utils import timezone
from PIL import Image
from django.urls import reverse
from django.utils.text import slugify



class Category(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args, **kwargs)
    class Meta:
        verbose_name_plural = "categories"     

    def get_absolute_url(self):
        return reverse('index')

class NewsStory(models.Model):
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField(default=timezone.now)
    content = models.TextField()
    # image = models.ImageField()
    image = models.ImageField(default=None, upload_to='story_pics')
    # author = models.CharField(max_length=200)
    author = models.ForeignKey(
        # get_user_model(),
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='published_stories'
    )
    category = models.ForeignKey('Category', default='Story', on_delete=models.SET_DEFAULT)

    def __str__(self):
        return f'{self.title} - by {self.author}'

    def save(self):
        super().save()
        # run the save method from the parents
        img = Image.open(self.image.path)
        if img.height > 600 or img.width >600:
            output_size = (600,  600)
            img.thumbnail(output_size)
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('news:story', kwargs={'pk':self.pk})

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Category
from django.db.utils import OperationalError, ProgrammingError

def categoryList():
    try: 
        choices = Category.objects.all().values_list('name', 'name')
        # select box needs double name to work
        choice_list=[]
        for item in choices:
            choice_list.append(item)
        return choice_list
    except (OperationalError, ProgrammingError): 
        return []


class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'category', 'content', 'image']
        labels = {
            'title': 'Story Title:',
            # 'author': 'Your name :',
            'pub_date': 'Publication Date',
            'content': 'Your story:',
            'image': 'Your image url',
        }
        widgets ={
            'title' : forms.TextInput(
                attrs={'class': 'text_field','placeholder' : 'Story Title',}),
            'category': forms.Select(
                choices=categoryList(), 
                # choices has to be befor attrs
                attrs={'class': 'select'}),
            'content' : forms.Textarea(
                attrs={
                    'class': 'text_field',
                    'placeholder' : 'Write your story here',
                    'size': '40'}),
            'pub_date': forms.DateInput(
                format=('%m/%d/%Y'),
                attrs={
                    'class': 'form-control text_field',
                    'placeholder': 'Select a date',
                    'type': 'date',
                }),          
        }
class UpdateStoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'content', 'image']
        labels = {
            'title': 'Story Title:',
            'content': 'Your story:',
            'image': 'Upload a new image',

        }
        widgets ={
            'title' : forms.TextInput(
                attrs={
                'class': 'text_field',
                'placeholder' : 'Story Title',
                }),
            'content' : forms.Textarea(
                attrs={
                    'class': 'text_field',
                    'placeholder' : 'Write your story here',
                    'size': '40'}),
        }
        
class AddCategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'Your category:',
        }
        widgets ={
            'name' : forms.TextInput(
                attrs={
                'class': 'text_field',
                }),
        }

she_codes_news/news/views.py
from django.views import generic

# from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render

# mixin to check if user logged in and a test on the user
from .models import NewsStory, Category
from .forms import StoryForm, UpdateStoryForm, AddCategoryForm
from users.models import CustomUser


class StoryView(generic.DetailView):
    # view of the story selected : DetailView
    model = NewsStory
    template_name = "news/story.html"
    context_object_name = "story"


class AddStoryView(LoginRequiredMixin, generic.CreateView):
    # create a new story : CreatwView
    form_class = StoryForm
    context_object_name = "storyForm"
    template_name = "news/createStory.html"
    success_url = reverse_lazy("news:index")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class IndexView(generic.ListView):
    # see a lsit of the stories ListView
    template_name = "news/index.html"
    cats = Category.objects.all()
    users = CustomUser.objects.all()


    def get_queryset(self):
        """Return all news stories."""
        return NewsStory.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context["latest_stories"] = NewsStory.objects.order_by("-pub_date")[:3]
        context["all_stories"] = NewsStory.objects.order_by("-pub_date")
        context["cat_menu"] = Category.objects.all()
        context["user_menu"] = CustomUser.objects.all()
        return context


def CategoryView(request, cats):
    category_post = NewsStory.objects.filter(category__slug=cats)
    # query the category field defined in the model

    return render(
        request, "news/categories.html", {"cats": cats, "category_post": category_post}
    )


class UpdateStoryView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    # update a post: UpdateView
    model = NewsStory
    form_class = UpdateStoryForm
    template_name = "news/updateStory.html"

    def get_absolute_url(self):
        return reverse_lazy("news:story", kwargs={"pk": self.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
        # test to get the post we are updating if the user is the author of the post with the mixin UserPassesTestMixin


class DeleteStoryView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    # Delete a post: DeleteView
    model = NewsStory
    template_name = "news/deleteStory.html"
    success_url = reverse_lazy("news:index")

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class AuthorView(generic.DetailView):
    template_name = "news/author.html"
    # model = settings.AUTH_USER_MODEL
    model = CustomUser
    context_object_name = "author"


class AddCategoryView(LoginRequiredMixin, generic.CreateView):
    model: Category
    form_class = AddCategoryForm
    template_name = "news/createCategory.html"
    success_url = reverse_lazy("news:addNewsStory")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

she_codes_news/news/templates/news/author.html
    {% extends "base.html" %}
    {% load static %}
    {% block title %}{{ story.autor }} stories{% endblock %}


    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}
    
    {% block content %}

    <div class="container">
        <h2>All the news written by {{ author.username }}</h2>
        <div class="container-profile-avatar">
            <img class="profile-avatar-post" src="{{ author.profile.avatar.url }}" alt="{{ author.username }} profile picture">
            <p>{{ author.profile.bio }}</p> 
        </div>
        <div class=" container-story-card"></div>
            <div class="all-stories">
                    {% for story in author.published_stories.all %}
                        {% include "./storyCard.html" with story=story %}
                    {% endfor %}
            </div>
        </div>
    </div>

    {% endblock %}

she_codes_news/news/templates/news/categories.html
{% extends "base.html" %}
<!-- load the tempalte base to inject this content -->
{% load static %}
{% block title %}She Codes News{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    
<div class="container">
    <h2 >Read all the news in the category <span class="category-title">{{ cats }}</span></h2>
    
    <div class=" container-story-card">
        <div class="all-stories">
            {% if category_post %}
                {% for story in category_post %}
                    {% include "./storyCard.html" with story=story %}`
                {% endfor %}
            {% else %}
                <p>There is no story published in this category. </br> Feel free to <a href="{% url 'news:addNewsStory' %}">create a new Story</a></p>
            {% endif %}
        </div>
        <div class="column-links">
            {% if user.is_authenticated %}
            <a href="{% url 'news:addNewsStory' %}">Write a new Story</a>
            {% else %}
            <a href="{% url 'login' %}">Login to create a Story</a>
            {% endif %}
            <!-- Categories -->
            {% if cat_menu %}
                {% for item in cat_menu %}
                <a href="{% url 'news:category' item.id %}">{{ item }}</a>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

she_codes_news/news/templates/news/createCategory.html
{% extends "base.html" %}
{% load static %}
{% block title %}Create a category{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h2> Create a category</h2>
        <form action="" method="post" id="create-story-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit your category">
        </form>
    </div>
{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% load static %}
{% block title %}Create your story{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<!-- {% if user.is_authenticated %} use mixin on views class to automatically redirect to login page if not logged in-->
    <div class="container">
        <h2> Be Creative!</h2>
        <p>You don't find the right category for your post?</p>
        <a href="{% url 'news:addCategory' %}">Add a category</a>
        <form action="" method="post" id="create-story-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit your Story">
        </form>
    </div>
<!-- {% else %} -->
    <a href="{% url 'login' %}?next={{request.path}}">Login to create a Story</a>
<!-- {% endif %}  -->
{% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}
{% load static %}
{% block title %}Delete your story{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h2> Are your sure you want to delete the post "{{ object.title }}</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Yes, Delete">
            <a class="" href="{% url 'news:story' object.id %}">Cancel></a>
            <!-- when not context defined in views, use object to target the actual post -->

        </form>
    </div>
{% endblock %}

she_codes_news/news/templates/news/index.html
    {% extends "base.html" %}
    <!-- load the tempalte base to inject this content -->
    {% load static %}
    {% block title %}She Codes News{% endblock %}


    {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content %}


    <div class="container-latest-stories">
        <h2>Latest News</h2>
        <div class="latest-stories">
            {% if latest_stories %}
            {% for story in latest_stories %}
            <!-- <p>{{ story.title }}</p> -->
            <!-- include the template storyCard for our story, look for position -->
            {% include "./storyImage.html" with story=story position=forloop.counter %}
            {% endfor %}
            {% else %}
            <p>No stories available.</p>
            {% endif %}
        </div>
    </div>

    <div class="container">  
        <h2>All the News</h2>
        <div class="container-story-card">
        <div class="all-stories">
            {% if latest_stories %}
            {% for story in all_stories %}
            {% include "./storyCard.html" with story=story %}
            {% endfor %}
            {% else %}
            <p>No stories available.</p>
            {% endif %}
        </div>
        <div class="column-links">
            {% if user.is_authenticated %}
            <a href="{% url 'news:addNewsStory' %}">Write a new Story</a>
            {% else %}
            <a href="{% url 'login' %}">Login to create a Story</a>
            {% endif %}
            <!-- Categories -->
            <h3> Categories</h3>
            {% if cat_menu %}
                {% for item in cat_menu %}
                <a href="{% url 'news:category' item.slug %}"><span class="category-title">{{ item }}</span></a>
                {% endfor %}
            {% endif %}
            <h3> Author</h3>
            {% if cat_menu %}
                {% for item in user_menu %}
                <a href="{% url 'news:author' item.pk %}"><span>{{ item }}</span></a>
                {% endfor %}
            {% endif %}
            </div>
        </div>
    </div>

    {% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ story.title }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="container-story">
    <h2>{{ story.title }}</h2>
    <div class="container-profile-avatar">
        <a href="{% url 'news:author' story.author.pk %}"><img class="profile-avatar-post" src="{{ story.author.profile.avatar.url }}"></a>
        <div>
            <p>Category<a href="{% url 'news:category' story.category %}"><span class="category-title"> {{ story.category}}</span></a></p>
            <p>Written by <a href="{% url 'news:author' story.author.pk %}"><span>{{ story.author }}</span></a></p>
            <p>{{ story.pub_date |date:" d F, Y"}}</p> 
        </div>
    </div>
    <div id="story-content">
        <img src="{{ story.image.url|default:'https://picsum.photos/600' }}"> 
        <!-- <img src="{% static '/news/images/placeholder-5.jpg' %}"> -->
        {{ story.content|linebreaks }}
    </div>
    </div>
    <div>
        {% if story.author == user %}
        <div>
            <a href="{% url 'news:updateStory' story.id %} " class="btn">Update</a>
            <a href="{% url 'news:deleteStory' story.id %} " class="btn">Delete</a>
        </div>    
        {% endif %}
    </div>
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card">
    <!-- include a link to the story with the id selected -->
    <div>   
        <a href="{% url 'news:author' story.author.pk %}"><img src="{{ story.author.profile.avatar.url }}" class="story-card-avatar" alt="{{story.author}} avatar"></a>
    </div>
    <div class="story-card-content">
        <img class="story-card-img" src="{{ story.image.url|default:'https://picsum.photos/600' }}"> 
        <div class="story-card-text">
            <p class="story-card-category"><a href="{% url 'news:category' story.category %}" >{{ story.category}}</a></p>
            <a href="{% url 'news:story' story.id %}" class="story-card-title"><h3>{{ story.title }}</h3></a>
            <p><a href="{% url 'news:author' story.author.pk %}" class="story-card-author">Written by {{ story.author }}</a></p>
            <p class="story-card-date">{{ story.pub_date |date:" d F, Y"}}</p>
        </div>
    </div>
</div>

she_codes_news/news/templates/news/storyImage.html
<div class="story-image">
    <!-- include a link to the story with the id selected -->
    <a href="{% url 'news:story' story.id %}">
        <div class="story-image-img">   
            <img src="{{ story.image.url|default:'https://picsum.photos/600' }}"> 
        </div>
        <div class="story-image-txt">
            <h3>{{ story.title }}</h3>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/updateStory.html
{% extends "base.html" %}
{% load static %}
{% block title %}Update your story{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Update your story</h2>
        <form action="" method="post" id="create-story-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
{% endblock %}